spring.datasource.url=jdbc:mysql://localhost:3306/dbSmart40
spring.datasource.username=root
spring.datasource.password=senai

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=18089
# IP principal usado pelo SmartService para enviar o pedido ao CLP de estoque
smart40.clp.ip=10.74.241.10
smart40.clp.estoque-ip=10.74.241.10
smart40.clp.processo-ip=10.74.241.20
smart40.clp.montagem-ip=10.74.241.30
smart40.clp.expedicao-ip=10.74.241.40
