spring.application.name=appsabancada
server.port=8088

spring.datasource.url=jdbc:mysql://localhost:3306/dbSmart40?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=America/Sao_Paulo&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=senai

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=America/Sao_Paulo
spring.jackson.time-zone=America/Sao_Paulo

app.seed.estoque=true

# IPs padrão dos CLPs Smart 4.0
smart40.clp.ip=10.74.241.10
smart40.clp.estoque-ip=10.74.241.10
smart40.clp.processo-ip=10.74.241.20
smart40.clp.montagem-ip=10.74.241.30
smart40.clp.expedicao-ip=10.74.241.40

api.estoque-url=http://localhost:8088/api/estoque
api.expedicao-url=http://localhost:8088/api/expedicao
